services:
  chatgpt-tarot-divination:
    image: ghcr.io/dreamhunter2333/chatgpt-tarot-divination:latest
    container_name: chatgpt-tarot-divination
    restart: always
    ports:
      - 8000:8000
    environment:
      - api_key=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
      - api_base=https://api.openai.com/v1 # optional
      - model=gpt-3.5-turbo # optional
      - rate_limit=10/minute # optional
      - user_rate_limit=600/hour # optional
      - github_client_id=xxx
      - github_client_secret=xxx
      - jwt_secret=secret
      - ad_client=ca-pub-xxx
      - ad_slot=123
